version: "1"

run:
  timeout: 5m

linters:
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - ineffassign
    - typecheck
    - unused
    - gosec
    - gocyclo
    - dupl
    - goconst
    - misspell
    - unparam
    - nakedret
    - prealloc
    - gocritic
    - revive

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
